[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.backends.legacy:build"

[project]
name = "feature-flag-sdk"
version = "0.1.0"
description = "Feature Flag Python SDK"
requires-python = ">=3.10"
dependencies = []

[tool.setuptools.packages.find]
where = ["."]
include = ["feature_flag_sdk*"]
